In [5]:
import pandas as pd

dfs = {
    "VAR": pd.read_csv("ta_var.tsv", sep="\t").drop(columns=["distractor_match_rate"]),
    "HOM": pd.read_csv("ta_hom.tsv", sep="\t"),
    "REL": pd.read_csv("ta_rel.tsv", sep="\t"),
}

ta = pd.concat(
    [df.set_index("model").round(1) for df in dfs.values()],
    axis=1,
    keys=dfs.keys()
).reset_index()

In [6]:
ta

                 model           VAR      HOM                        REL  \
                       term_accuracy Südtirol    DE    AT    CH Südtirol
0          Cohere CAT+          53.1     62.4  63.8  68.0  65.2     82.0
1           Command A+          56.6     62.1  49.4  64.8  58.2     81.3
2         CUNI-EdUKate          27.7     22.2  27.1  21.6  31.6     28.9
3           CUNI-MH-v3          30.6     28.0  28.4  26.0  34.8     30.4
4      DeepSeek V4 Pro          64.0     75.7  82.0  82.8  81.6     90.1
5            Dubformer          63.7     65.9  74.6  77.2  71.5     89.0
6       Gemini 3.1 Pro          76.4     77.8  86.5  87.2  88.3     94.9
7         Gemma 4 - 4B          54.6     50.3  53.0  50.0  51.6     78.0
8        Gemma 4 - 31B          61.0     64.7  72.9  69.2  65.2     85.0
9           GLM 4 - 9B          45.5     38.2  39.5  34.0  33.6     62.6
10     GoogleTranslate          36.0     29.8  32.0  27.2  37.9     33.3
11             GPT 5.5          72.3     80.1  86.7  88.8  87.5     94.9
12         GPT OSS 20B          54.7     57.5  53.9  56.4  54.7     72.5
13        GPT OSS 120B          56.9     64.2  66.3  68.4  63.7     76.9
14   Ministral 3 - 14B          54.5     48.6  52.2  51.2  49.2     73.6
15  Mistral Medium 3.5          61.9     57.5  59.4  63.2  58.6     84.6
16       Qingqiu-MT-9B          51.7     57.5  62.2  60.0  59.0     78.8
17       Qwen 3.5 - 9b          48.0     48.3  51.7  48.0  52.0     70.3
18      Qwen 3.6 - 27b          55.8     54.0  61.3  61.2  53.1     78.8
19        SalamandraTA          51.7     54.9  60.2  54.8  54.7     67.4
20     Tiny Aya Global          42.2     35.8  40.1  36.8  38.3     51.3
21            Tower 9B          49.1     49.4  51.7  48.8  52.7     74.4
22               TRIVE          72.2     78.0  86.7  86.8  85.6     94.5
23              UvA-MT          59.9     67.9  74.0  79.2  72.7     91.6
24                Mean           NaN     55.4  59.0  58.8  58.4     73.6


      DE    AT    CH
0   86.1  82.4  84.4
1   55.7  64.7  76.6
2   18.0  23.5  17.2
3   27.0  29.4  25.0
4   95.1  89.7  93.8
5   92.6  92.6  89.1
6   94.3  95.6  96.9
7   77.9  63.2  68.8
8   85.2  80.9  87.5
9   49.2  47.1  51.6
10  35.2  33.8  28.1
11  94.3  95.6  96.9
12  73.8  73.5  68.8
13  71.3  77.9  78.1
14  74.6  82.4  76.6
15  85.2  86.8  81.2
16  70.5  63.2  67.2
17  69.7  60.3  70.3
18  80.3  76.5  82.8
19  68.8  63.2  68.8
20  50.0  44.1  43.8
21  77.9  58.8  71.9
22  94.3  94.1  95.3
23  86.9  86.8  89.1
24  71.4  69.4  71.2

In [11]:
ta.to_csv("2_ta.tsv", sep="\t", index=False)

NameError: name 'fig' is not defined

In [7]:
dfs = {
    "VAR": pd.read_csv("bleu_var.tsv", sep="\t"),
    "HOM": pd.read_csv("bleu_hom.tsv", sep="\t"),
    "REL": pd.read_csv("bleu_rel.tsv", sep="\t"),
}

bleu = pd.concat(
    [df.set_index("model").round(1) for df in dfs.values()],
    axis=1,
    keys=dfs.keys()
).reset_index()

In [8]:
bleu

                 model   VAR   HOM                     REL
                          ST    ST    DE    AT    CH    ST    DE    AT    CH
0          Cohere CAT+  35.2  36.7  39.8  34.9  37.4  39.1  36.7  40.2  41.0
1           Command A+  32.7  36.6  31.4  31.9  33.8  38.8  30.6  36.5  34.5
2         CUNI-EdUKate  26.6  27.9  26.0  21.7  25.4  30.8  27.2  28.3  29.6
3           CUNI-MH-v3  29.0  29.6  29.8  25.7  28.4  31.7  30.2  29.0  30.5
4      DeepSeek V4 Pro  44.3  45.3  52.9  44.0  49.1  47.0  44.9  48.5  47.6
5            Dubformer  42.6  43.2  48.9  41.0  45.8  46.2  44.0  46.1  46.1
6       Gemini 3.1 Pro  48.4  50.2  63.4  50.1  60.1  53.2  51.8  54.2  54.1
7        Gemma 4 - 31B  38.0  39.8  40.5  35.6  38.3  42.8  39.4  41.7  43.6
8         Gemma 4 - 4B  31.4  32.0  30.7  27.0  28.5  35.2  30.6  32.1  34.9
9           GLM 4 - 9B  24.5  25.4  25.4  21.1  23.2  28.2  23.9  25.4  28.3
10     GoogleTranslate  28.1  27.4  28.3  23.4  25.9  29.7  28.8  31.8  30.3
11             GPT 5.5  47.4  50.1  60.1  50.6  60.7  50.8  49.9  53.2  57.2
12        GPT OSS 120B  31.8  33.8  35.2  28.9  29.3  36.3  31.0  33.8  33.5
13         GPT OSS 20B  25.1  26.3  25.9  20.8  21.1  29.6  25.4  24.1  25.4
14   Ministral 3 - 14B  26.9  27.3  27.5  23.8  24.5  29.4  25.3  29.5  22.9
15  Mistral Medium 3.5  38.1  40.1  45.2  37.4  39.4  40.8  39.9  42.1  43.9
16       Qingqiu-MT-9B  33.0  35.2  34.7  29.1  30.6  37.3  31.2  34.6  32.4
17       Qwen 3.5 - 9b  27.1  28.2  29.4  22.6  25.4  28.9  27.8  26.9  26.3
18      Qwen 3.6 - 27b  34.1  35.0  36.5  30.9  32.5  37.2  33.3  35.8  33.9
19        SalamandraTA  30.8  31.8  35.4  27.9  30.3  34.0  32.1  35.0  33.0
20     Tiny Aya Global  21.8  14.3  25.7  20.8  22.4  29.5  26.0  25.6  27.6
21            Tower 9B  33.3  34.0  36.4  30.4  32.6  36.5  34.4  37.1  38.6
22               TRIVE  46.8  50.4  57.5  47.0  58.3  51.2  49.9  52.7  52.6
23              UvA-MT  40.6  42.6  49.8  43.9  49.5  44.5  42.8  47.7  49.4

In [10]:
bleu.to_csv("2_bleu.tsv", sep="\t", index=False)